-- 코드를 작성해주세요
SELECT P.ITEM_ID, P.ITEM_NAME, P.RARITY
FROM ITEM_TREE AS I
-- 부모 아이템의 희귀도가 RARE
JOIN ITEM_INFO AS PARENT ON PARENT.ITEM_ID = I.PARENT_ITEM_ID
JOIN ITEM_INFO AS P ON P.ITEM_ID = I.ITEM_ID
WHERE PARENT.RARITY = 'RARE'
ORDER BY P.ITEM_ID DESC;